export default [
  {
    address: '9138 Stiedemann Ports',
    avatar: 'https://robohash.org/possimusdoloresid.png?size=300x300&set=set1',
    city: 'Norvalville',
    email: 'keven@grady.net',
    name: 'Ms. Alfonzo Stoltenberg',
    title: 'Direct Implementation Producer',
  },
  {
    address: '166 Waters Falls',
    avatar: 'https://robohash.org/perferendissapienteodit.png?size=300x300&set=set1',
    city: 'Melisaton',
    email: 'clementina_ryan@dooley.com',
    name: 'Lelia Willms',
    title: 'Internal Security Assistant',
  },
  {
    address: '1846 Murazik Hill',
    avatar: 'https://robohash.org/voluptatibusearumconsequatur.png?size=300x300&set=set1',
    city: 'Nealburgh',
    email: 'betsy@walsh.io',
    name: 'Jermain Gorczany',
    title: 'National Tactics Designer',
  },
  {
    address: '3764 Kyler Grove',
    avatar: 'https://robohash.org/solutaametminima.png?size=300x300&set=set1',
    city: 'Terrellview',
    email: 'maximillia@bednar.net',
    name: 'Zakary White',
    title: 'Dynamic Web Associate',
  },
  {
    address: '73918 Roxanne Port',
    avatar: 'https://robohash.org/nesciuntetmaxime.png?size=300x300&set=set1',
    city: 'Port Ottisstad',
    email: 'dale@reichel.name',
    name: 'Rosa Cronin DVM',
    title: 'Future Configuration Designer',
  },
  {
    address: '58813 Kuvalis Knolls',
    avatar: 'https://robohash.org/blanditiisvoluptatescupiditate.png?size=300x300&set=set1',
    city: 'Darianside',
    email: 'flavie@sanford.co',
    name: 'Mortimer Haley',
    title: 'National Program Manager',
  },
  {
    address: '9686 Alysa Point',
    avatar: 'https://robohash.org/veniamaccusamusminus.png?size=300x300&set=set1',
    city: 'Port Judd',
    email: 'geo.gleichner@roobheller.net',
    name: 'Peggie Nitzsche',
    title: 'District Response Strategist',
  },
  {
    address: '602 Schuster Shoal',
    avatar: 'https://robohash.org/isteeasunt.png?size=300x300&set=set1',
    city: 'Emardshire',
    email: 'ardith@armstrong.name',
    name: 'Mrs. Clifford Weissnat',
    title: 'District Operations Facilitator',
  },
  {
    address: '233 Edythe Glens',
    avatar: 'https://robohash.org/excepturirepudiandaeiusto.png?size=300x300&set=set1',
    city: 'Zemlakview',
    email: 'lela@nicolas.biz',
    name: 'Ms. Edmund Schamberger',
    title: 'National Group Manager',
  },
  {
    address: '9818 Weimann Summit',
    avatar: 'https://robohash.org/quietvelit.png?size=300x300&set=set1',
    city: 'North Keontown',
    email: 'korbin@hansen.net',
    name: 'Gudrun Borer',
    title: 'District Factors Administrator',
  },
  {
    address: '2649 Parker Point',
    avatar: 'https://robohash.org/deseruntvoluptatematque.png?size=300x300&set=set1',
    city: 'Batzland',
    email: 'destinee.heidenreich@schulistlockman.io',
    name: 'Miss Breanne Gottlieb',
    title: 'District Applications Supervisor',
  },
  {
    address: '2157 Kasey Mission',
    avatar: 'https://robohash.org/etconsecteturvero.png?size=300x300&set=set1',
    city: 'Doylestad',
    email: 'alfonzo_stehr@macgyver.org',
    name: 'Lauriane Douglas II',
    title: 'Legacy Intranet Analyst',
  },
  {
    address: '187 Kris Spur',
    avatar: 'https://robohash.org/eligendiinsoluta.png?size=300x300&set=set1',
    city: 'Lake Jana',
    email: 'jaunita_blick@jacobs.org',
    name: 'Giovanny Lesch',
    title: 'International Intranet Analyst',
  },
  {
    address: '77853 Kyleigh Grove',
    avatar: 'https://robohash.org/suscipitminimaet.png?size=300x300&set=set1',
    city: 'East Amaya',
    email: 'samir@gloversmith.biz',
    name: 'Mrs. Trace Turner',
    title: 'Forward Program Supervisor',
  },
  {
    address: '67841 Vernon Causeway',
    avatar: 'https://robohash.org/omnismaioresarchitecto.png?size=300x300&set=set1',
    city: 'West Alessandra',
    email: 'david@bailey.name',
    name: 'Miss Gerard Mraz',
    title: 'Direct Infrastructure Director',
  },
  {
    address: '546 Clemmie Pines',
    avatar: 'https://robohash.org/nonconsequaturprovident.png?size=300x300&set=set1',
    city: 'Lillieland',
    email: 'noel@mccullough.biz',
    name: 'Doyle Jacobs',
    title: 'Principal Mobility Director',
  },
  {
    address: '14369 Gleason Harbor',
    avatar: 'https://robohash.org/dolorestaliquid.png?size=300x300&set=set1',
    city: 'Port Karlview',
    email: 'karl@braun.io',
    name: 'Keshawn Witting',
    title: 'Product Accounts Agent',
  },
  {
    address: '1142 Veum Shoals',
    avatar: 'https://robohash.org/amettemporeiure.png?size=300x300&set=set1',
    city: 'Stonechester',
    email: 'rory_mccullough@kertzmann.org',
    name: 'Raoul Kirlin',
    title: 'Chief Optimization Architect',
  },
  {
    address: '87959 Howe Manors',
    avatar: 'https://robohash.org/modidoloremipsum.png?size=300x300&set=set1',
    city: 'North Wendell',
    email: 'finn_pacocha@rogahn.net',
    name: 'Roderick O\'Reilly',
    title: 'Forward Security Planner',
  },
  {
    address: '88502 Von Path',
    avatar: 'https://robohash.org/nonsimiliqueet.png?size=300x300&set=set1',
    city: 'Adalbertoville',
    email: 'macey@bergnaum.io',
    name: 'Korbin Heidenreich',
    title: 'Chief Brand Coordinator',
  },
  {
    address: '45421 Walter Estates',
    avatar: 'https://robohash.org/rerumexercitationemut.png?size=300x300&set=set1',
    city: 'Port Antoinettechester',
    email: 'karlie.reichert@jones.io',
    name: 'Nathanial Swift',
    title: 'National Applications Consultant',
  },
  {
    address: '95648 Jones Spurs',
    avatar: 'https://robohash.org/ullamvitaeveritatis.png?size=300x300&set=set1',
    city: 'Jadestad',
    email: 'justine@herman.org',
    name: 'Elijah Heller',
    title: 'Lead Security Analyst',
  },
  {
    address: '4181 Kautzer Divide',
    avatar: 'https://robohash.org/itaqueetest.png?size=300x300&set=set1',
    city: 'Mayefort',
    email: 'wyatt.gislason@halvorsondonnelly.info',
    name: 'Aurelia Sipes',
    title: 'Legacy Creative Coordinator',
  },
  {
    address: '385 Schimmel Gateway',
    avatar: 'https://robohash.org/quasiestut.png?size=300x300&set=set1',
    city: 'Vernonside',
    email: 'bo_rolfson@rath.com',
    name: 'Tyra Schneider',
    title: 'Product Assurance Orchestrator',
  },
  {
    address: '203 Frida Lakes',
    avatar: 'https://robohash.org/mollitiaremsint.png?size=300x300&set=set1',
    city: 'East Anabel',
    email: 'kirstin@schulist.io',
    name: 'Myrtice Nikolaus',
    title: 'Lead Operations Technician',
  },
];
